export default {
  menuIcon: require('./menuIcon.png'),
  searchIcon: require('./searchIcon.png'),
  movieDbIcon: require('./movieDBIcon.png'),
  expandIcon: require('./expandIcon.png'),
  threeDotIcon: require('./threeDotIcon.png'),
  playIcon: require('./playIcon.png'),
  backIcon: require('./backIcon.png'),
  movieDbIcon3x: require('./movieDB3x.png'),
  movieDbIcon2x: require('./movieDB2x.png'),
  homeIcon: require('./homeIcon.png'),
  trailerIcon: require('./trailerIcon.png'),
  moviesIcon: require('./moviesIcon.png'),
  communityIcon: require('./communityIcon.png'),
  notFound: require('./notFoundIcon.png'),
};
