export default {
  menuIcon: require('./menuIcon.png'),
  searchIcon: require('./searchIcon.png'),
  movieDbIcon: require('./movieDBIcon.png'),
  expandIcon: require('./expandIcon.png'),
  threeDotIcon: require('./threeDotIcon.png'),
  playIcon: require('./playIcon.png'),
  backIcon: require('./backIcon.png'),
  movieDbIcon3x: require('./movieDB3x.png'),
  movieDbIcon2x: require('./movieDB2x.png'),
  homeIcon: require('./homeIcon.png'),
  trailerIcon: require('./trailerIcon.png'),
  moviesIcon: require('./moviesIcon.png'),
  communityIcon: require('./communityIcon.png'),
  notFound: require('./notFoundIcon.png'),
  comingSoon: require('./comingSoon.png'),
  logout: require('./logout.png'),
  trending: require('./trending.png'),
  tv: require('./tv.png'),
  avatar: require('./user.png'),
  chatBackground: require('./chatBackground.png'),
  send: require('./send.png'),
  location: require('./share.png'),
  camera: require('./camera.png'),
  attach: require('./attach.png'),
  gallery: require('./gallery.png'),
  dotMenu: require('./dots.png'),
};
