export default {
  posterImageUrl: 'https://image.tmdb.org/t/p/w342',
  backDropImageUrl: 'https://image.tmdb.org/t/p/w780',
  movieTrailerBackgroundImage:
    'https://image.tmdb.org/t/p/w780/ic8h5oYQWwqQWPyfpZUSomZTdao.jpg',
  baseUrl: 'https://api.themoviedb.org/3',
  popularMoviePath: '/movie/popular',
  freeToWatchMoviePath: '/discover/movie',
  trendingMoviePath: '/trending/all/day',
  apiKey: '?api_key=1b798ccdd4a124b7939797f1601930cc',
  language: 'en-US',
  page: '&page=',
  popularStreamingMoviePath: '/movie/popular',
  popularTvMoviePath: '/tv/popular',
  discoverMoviePath: '/discover/movie',
  discoverTvPath: '/discover/tv',
  popularTheaterMoviePath: 'movie/now_playing',
  latestTrailerPath: '/movie/upcoming',
  trendingDayMoviePath: '/trending/all/day',
  trendingWeekMoviePath: '/trending/all/week',
  defaultPage: 1,
  watchFree: '&sort_by=popularity.desc&with_watch_monetization_types=free',
  watchRent: '&sort_by=popularity.desc&with_watch_monetization_types=rent',
  trailerWatchRent:
    '&sort_by=release_date.asc&with_watch_monetization_types=rent',
  trailerOnTv: '&sort_by=first_air_date.desc',
};
