import appConstants from './appConstants';
import {
  AuthReduxDataType,
  AuthSagaDataType,
  AuthStateDataType,
  Credentials,
  DataType,
  DetailPathDataType,
  DetailResponseGenerator,
  DetailStateDataType,
  DetailStoreDataType,
  DropDownDataType,
  FormTypeProps,
  FreeMovieDataType,
  HeaderDataType,
  ListContainerDataType,
  ListItemDataType,
  ListItemType,
  MovieDetailsDataType,
  MovieResponseGenerator,
  MovieSagaDataType,
  MovieStoreDataType,
  NavigationDataType,
  NavigationScreenType,
  PopularDataType,
  RootState,
  RouteDataType,
  TrailerDataType,
  TrendingDataType,
  TabBarIconDataType,
} from './appTypes';
import navigationStrings from './navigationStrings';
import { filterData, movieDetails } from './staticData';
import strings from './strings';

export { appConstants, navigationStrings, filterData, movieDetails, strings };
export type {
  AuthReduxDataType,
  AuthSagaDataType,
  AuthStateDataType,
  Credentials,
  DataType,
  DetailPathDataType,
  DetailResponseGenerator,
  DetailStateDataType,
  DetailStoreDataType,
  DropDownDataType,
  FormTypeProps,
  FreeMovieDataType,
  HeaderDataType,
  ListContainerDataType,
  ListItemDataType,
  ListItemType,
  MovieDetailsDataType,
  MovieResponseGenerator,
  MovieSagaDataType,
  MovieStoreDataType,
  NavigationDataType,
  NavigationScreenType,
  PopularDataType,
  RootState,
  RouteDataType,
  TrailerDataType,
  TrendingDataType,
  TabBarIconDataType,
};
