import appConstants from './appConstants';
import {
  AuthReduxDataType,
  AuthSagaDataType,
  AuthStateDataType,
  ChatHeaderDataType,
  Credentials,
  CustomDrawerDataType,
  DataType,
  DetailPathDataType,
  DetailResponseGenerator,
  DetailStateDataType,
  DetailStoreDataType,
  DrawerStateDataType,
  DropDownDataType,
  FormTypeProps,
  FreeMovieDataType,
  HeaderDataType,
  ListContainerDataType,
  ListDataType,
  ListItemDataType,
  ListItemType,
  LoaderDataType,
  LoadingStateProps,
  MessageDataType,
  MovieDataType,
  MovieDetailsDataType,
  MovieResponseGenerator,
  MovieSagaDataType,
  MovieStoreDataType,
  NavigationDataType,
  NavigationScreenType,
  PopularDataType,
  RootState,
  RouteDataType,
  SearchFunctionDataType,
  SearchModalDataType,
  SkeletonProps,
  TabBarIconDataType,
  TrailerDataType,
  TrendingDataType,
} from './appTypes';
import navigationStrings from './navigationStrings';
import { filterData, genres, messagesData, usersList } from './staticData';
import strings from './strings';

export {
  appConstants,
  navigationStrings,
  filterData,
  genres,
  strings,
  usersList,
  messagesData,
};
export type {
  AuthReduxDataType,
  AuthSagaDataType,
  AuthStateDataType,
  ChatHeaderDataType,
  Credentials,
  CustomDrawerDataType,
  DataType,
  DetailPathDataType,
  DetailResponseGenerator,
  DetailStateDataType,
  DetailStoreDataType,
  DropDownDataType,
  FormTypeProps,
  FreeMovieDataType,
  HeaderDataType,
  ListContainerDataType,
  ListDataType,
  ListItemDataType,
  ListItemType,
  LoaderDataType,
  MessageDataType,
  MovieDataType,
  MovieDetailsDataType,
  MovieResponseGenerator,
  MovieSagaDataType,
  MovieStoreDataType,
  NavigationDataType,
  NavigationScreenType,
  PopularDataType,
  RootState,
  RouteDataType,
  SearchFunctionDataType,
  SearchModalDataType,
  TabBarIconDataType,
  TrailerDataType,
  TrendingDataType,
  LoadingStateProps,
  SkeletonProps,
  DrawerStateDataType,
};
