export default {
  Home: 'Home',
  Details: 'Details',
  SignUp: 'SignUp',
  Login: 'Login',
  HomeTab: 'HomeTab',
  Trailers: 'Trailers',
  Movies: 'Movies',
  Community: 'Community',
  HomeDrawer: 'HomeDrawer',
  Chat: 'Chat',
  Location: 'Location',
  ChatMessage: 'ChatMessage',
  NewGroup: 'NewGroup',
  ProfileInfo: 'ProfileInfo',
};
