import { strings } from '../constants';

export const filterData = {
  popularMovieTrailerFilterData: [
    { id: 0, name: strings.streaming },
    { id: 1, name: strings.onTv },
    { id: 2, name: strings.forRent },
    { id: 3, name: strings.inTheaters },
  ],
  freeToWatchMovieFilterData: [
    { id: 0, name: strings.movies },
    { id: 1, name: strings.tv },
  ],
  trendingFilterData: [
    { id: 0, name: strings.today },
    { id: 1, name: strings.thisWeek },
  ],
};

export const movieData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
      genre_ids: [28, 12],
      id: 335787,
      original_language: 'en',
      original_title: 'Uncharted',
      overview:
        'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
      popularity: 5250.828,
      poster_path: '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
      release_date: '2022-02-10',
      title: 'Uncharted',
      video: false,
      vote_average: 7.2,
      vote_count: 1653,
    },
    {
      adult: false,
      backdrop_path: '/5P8SmMzSNYikXpxil6BYzJ16611.jpg',
      genre_ids: [80, 9648, 53],
      id: 414906,
      original_language: 'en',
      original_title: 'The Batman',
      overview:
        'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
      popularity: 5011.012,
      poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
      release_date: '2022-03-01',
      title: 'The Batman',
      video: false,
      vote_average: 7.8,
      vote_count: 4252,
    },
    {
      adult: false,
      backdrop_path: '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
      genre_ids: [28, 878, 35, 10751, 12],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      overview:
        'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
      popularity: 5170.978,
      poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      release_date: '2022-03-30',
      title: 'Sonic the Hedgehog 2',
      video: false,
      vote_average: 7.7,
      vote_count: 911,
    },
    {
      adult: false,
      backdrop_path: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      popularity: 3782.14,
      poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      release_date: '2021-12-15',
      title: 'Spider-Man: No Way Home',
      video: false,
      vote_average: 6.1,
      vote_count: 12402,
    },
  ],
  total_pages: 33431,
  total_results: 668620,
};

export const movieTrailerData = {
  dates: {
    maximum: '2022-06-04',
    minimum: '2022-05-08',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
      genre_ids: [16, 35, 28, 10751, 80],
      id: 629542,
      original_language: 'en',
      original_title: 'The Bad Guys',
      overview:
        'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
      popularity: 4294.361,
      poster_path: '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
      release_date: '2022-03-17',
      title: 'The Bad Guys',
      video: false,
      vote_average: 7.8,
      vote_count: 271,
    },
    {
      adult: false,
      backdrop_path: '/2n95p9isIi1LYTscTcGytlI4zYd.jpg',
      genre_ids: [18, 53, 80],
      id: 799876,
      original_language: 'en',
      original_title: 'The Outfit',
      overview:
        'Leonard is an English tailor who used to craft suits on London’s world-famous Savile Row. After a personal tragedy, he’s ended up in Chicago, operating a small tailor shop in a rough part of town where he makes beautiful clothes for the only people around who can afford them: a family of vicious gangsters.',
      popularity: 2429.97,
      poster_path: '/lZa5EB6PVJBT5mxhgZS5ftqdAm6.jpg',
      release_date: '2022-02-25',
      title: 'The Outfit',
      video: false,
      vote_average: 7,
      vote_count: 182,
    },
    {
      adult: false,
      backdrop_path: '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
      genre_ids: [28, 12, 14, 18],
      id: 639933,
      original_language: 'en',
      original_title: 'The Northman',
      overview:
        "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
      popularity: 418.452,
      poster_path: '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
      release_date: '2022-04-07',
      title: 'The Northman',
      video: false,
      vote_average: 7.7,
      vote_count: 438,
    },
    {
      adult: false,
      backdrop_path: '/geYUecpFI2AonDLhjyK9zoVFcMv.jpg',
      genre_ids: [16, 28, 12, 9648],
      id: 810693,
      original_language: 'ja',
      original_title: '劇場版 呪術廻戦 0',
      overview:
        "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
      popularity: 410.614,
      poster_path: '/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg',
      release_date: '2021-12-24',
      title: 'Jujutsu Kaisen 0',
      video: false,
      vote_average: 7.7,
      vote_count: 126,
    },
    {
      adult: false,
      backdrop_path: '/9SISFlf6SEiIb7CMk8h0Gu3NYow.jpg',
      genre_ids: [27, 53],
      id: 745881,
      original_language: 'th',
      original_title: 'ร่างทรง',
      overview:
        'A horrifying story of a shaman’s inheritance in the Isan region of Thailand. But the goddess that appears to have taken possession of a family member turns out not be as benevolent as it first appears.',
      popularity: 292.703,
      poster_path: '/tWoSE8SH6XhgWKHIL3p0sj7lA3V.jpg',
      release_date: '2021-07-14',
      title: 'The Medium',
      video: false,
      vote_average: 7.1,
      vote_count: 299,
    },
    {
      adult: false,
      backdrop_path: '/9Fv41b6nEBGrSprFDVpO6GA94Wi.jpg',
      genre_ids: [12, 28, 878, 53],
      id: 507086,
      original_language: 'en',
      original_title: 'Jurassic World Dominion',
      overview:
        'Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.',
      popularity: 244.668,
      poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
      release_date: '2022-06-01',
      title: 'Jurassic World Dominion',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/ic8h5oYQWwqQWPyfpZUSomZTdao.jpg',
      genre_ids: [18, 53],
      id: 821427,
      original_language: 'en',
      original_title: 'The Novice',
      overview:
        "A college freshman joins her university's rowing team and undertakes an obsessive physical and psychological journey to make it to the top varsity boat, no matter the cost.",
      popularity: 263.56,
      poster_path: '/zIkGGiQBNITG9vVxgmf6MXQ1gT1.jpg',
      release_date: '2021-12-17',
      title: 'The Novice',
      video: false,
      vote_average: 6.5,
      vote_count: 49,
    },
  ],
  total_pages: 21,
  total_results: 414,
};
