export default {
  whatsPopular: "What's Popular",
  freeToWatch: 'Free To Watch',
  latestTrailers: 'Latest Trailers',
  streaming: 'Streaming',
  onTv: 'On TV',
  forRent: 'For Rent',
  inTheaters: 'In Theaters',
  trending: 'Trending',
  tv: 'TV',
  today: 'Today',
  thisWeek: 'This Week',
  movies: 'Movies',
  homeScreen: 'HomeScreen',
  detailScreen: 'DetailScreen',
  officialTrailer: 'Official Trailer',
  clientError: 'Client Error',
  networkError: 'Network Error',
  connectionError: 'Connection Error',
  serverError: 'Server Error',
  errorMessage: 'Something went wrong',
  pageErrorMessage: 'Page not Found',
  networkErrorMessage: 'Please check your internet connection',
  serverErrorMessage: 'Something went wrong',
  userScore: 'User Score',
  playTrailer: 'Play Trailer',
  certification: 'NR',
  overview: 'OverView',
  director: 'Director',
  dot: '⚈',
  email: 'Email',
  emailCamel: 'email',
  username: 'Username',
  password: 'Password',
  confirmPasswordPlaceholder: 'Confirm Password',
  passwordCamel: 'password',
  login: 'Login',
  loginCamel: 'login',
  signUp: 'Sign Up',
  signUpCamel: 'signUp',
  emailRequired: 'Please Enter Email Address',
  emailFormat: 'Email Should Be Like abc@gmail.com',
  usernameFormat: 'Username Must Be 6 Letter',
  passwordRequired: 'Please Enter Password',
  passwordLength: 'Password Should Be 8 Characters Long',
  passwordRegex: /^((?=.*\d)(?=.*[A-Z])(?=.*\W).{8,})$/,
  emailRegex: /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(.\w\w+)+$/,
  passwordRegexMatch:
    'Password Must Contain At Least 1 Uppercase,1 Lowercase, 1 Special Character & a Number',
  accountNotExist: "Don't Have Account?",
  createAccount: 'Create One!',
  createYourAccount: 'Create Your Account',
  confirmPassword: 'Password & Confirm Password Should Be Same',
  loginError: 'Invalid Credentials or User Not Found',
  signUpError: 'Account Already Exist!',
  movieScreen: 'MoviesScreen',
  trailersScreen: 'TrailersScreen',
  communityScreen: 'CommunityScreen',
  cancel: 'Cancel',
  search: 'Search',
  home: 'Home',
  tvShows: 'TV Shows',
  people: 'People',
  logout: 'Logout',
  chatScreen: 'Chat Screen',
  lastMessage: 'last Message here for the information',
  onlineStatus: 'Online',
  chatPlaceholder: 'Type Something...',
  tabRoute: 'TabRoot',
  warning: 'Warning',
  confirm: 'Confirm Logout?',
  ok: 'OK',
  tint: 'tint',
  color: 'color',
  back: 'back',
  noUserFound: 'No Users Found!',
  chatUsers: 'ChatUsers',
  user: 'User',
  chatCollection: 'Chat',
  you: 'You: ',
  startConversation: 'Start Conversation',
  yesterday: 'Yesterday',
  emptyString: '',
};
