export default {
  whatsPopular: "What's Popular",
  freeToWatch: 'Free To Watch',
  latestTrailers: 'Latest Trailers',
  streaming: 'Streaming',
  onTv: 'On TV',
  forRent: 'For Rent',
  inTheaters: 'In Theaters',
  trending: 'Trending',
  tv: 'TV',
  today: 'Today',
  thisWeek: 'This Week',
  movies: 'Movies',
  homeScreen: 'HomeScreen',
  detailScreen: 'DetailScreen',
  officialTrailer: 'Official Trailer',
  clientError: 'Client Error',
  networkError: 'Network Error',
  connectionError: 'Connection Error',
  serverError: 'Server Error',
  errorMessage: 'Something went wrong',
  pageErrorMessage: 'Page not Found',
  networkErrorMessage: 'Please check your internet connection',
  serverErrorMessage: 'Something went wrong',
};
